# List and operation on list

In [ ]:
# LIST
ROll_NO=[1,2,3,4,5];name=["Shrikant","Ajay","Sanket"]
list=[ROll_NO,name]
print(list)
list[1][0]

In [77]:
list=["H","B","C"]
list[0]="A"
len(list)

3

In [75]:
list.append("D")
list


['C', 'D', 'D', 'D']

In [60]:
list.insert(4,"E")
list

['A', 'B', 'C', 'D', 'E']

In [61]:
del list[4]
list

['A', 'B', 'C', 'D']

In [62]:
list.remove("B")
list

['A', 'C', 'D']

In [63]:
list.pop(0)

'A'

# Tuple

In [66]:
tuple=("Name","shrikant","age","23")
tuple

('Name', 'shrikant', 'age', '23')

In [72]:
tuple[0:3];tuple[:3]

('Name', 'shrikant', 'age')

In [73]:
len(list)

2

In [81]:
min((1,2,3,4,5));max((5,6,4,8,55))

55

In [89]:
a=("shrikant");b=(" deshmukh")

In [90]:
a+b

'shrikant deshmukh'

# Dictionary


In [33]:
Fuel_type={"petrol":1,"Diesel":2,"CNG":3}

In [34]:
Fuel_type

{'petrol': 1, 'Diesel': 2, 'CNG': 3}

In [35]:
print(Fuel_type['petrol'])

1


In [36]:
Fuel_type.keys()

dict_keys(['petrol', 'Diesel', 'CNG'])

In [37]:
Fuel_type.values()

dict_values([1, 2, 3])

In [38]:
Fuel_type.items()

dict_items([('petrol', 1), ('Diesel', 2), ('CNG', 3)])

In [39]:
Fuel_type['electric']=4;print(Fuel_type)

{'petrol': 1, 'Diesel': 2, 'CNG': 3, 'electric': 4}


In [40]:
Fuel_type.update({'machine':5});print(Fuel_type)

{'petrol': 1, 'Diesel': 2, 'CNG': 3, 'electric': 4, 'machine': 5}


In [41]:
Fuel_type['CNG']=6;print(Fuel_type)

{'petrol': 1, 'Diesel': 2, 'CNG': 6, 'electric': 4, 'machine': 5}


In [42]:
del Fuel_type['petrol'];print(Fuel_type)

{'Diesel': 2, 'CNG': 6, 'electric': 4, 'machine': 5}


# SET

In [45]:
age={12,52,42,25,16};print(age)

{42, 12, 16, 52, 25}


In [47]:
age.add(2);print(age)

{2, 42, 12, 16, 52, 25}


In [56]:
name={'shri','kiran','ram'};print(name)

{'shri', 'kiran', 'ram'}


In [57]:
name.add('rohan');print(name)

{'rohan', 'shri', 'kiran', 'ram'}


In [59]:
name.discard('rohan');print(name)

{'shri', 'kiran', 'ram'}


In [62]:
name.clear();print(name)

set()


In [65]:
name={'rohan','shri','kiran','ram'};name1={'rohan', 'shri', 'prem', 'preetam'}

In [66]:
name.union(name1)

{'kiran', 'preetam', 'prem', 'ram', 'rohan', 'shri'}

In [67]:
name.intersection(name1)

{'rohan', 'shri'}

In [68]:
name.difference(name1)

{'kiran', 'ram'}

In [69]:
name.symmetric_difference(name1)

{'kiran', 'preetam', 'prem', 'ram'}

# Numpy 


In [2]:
import numpy as np

In [8]:
x=np.array([1,2,3,4,5]);print(x)

[1 2 3 4 5]


In [10]:
y=np.array([1,'g',2]);print(y)

['1' 'g' '2']


In [12]:
print(type(x))

<class 'numpy.ndarray'>


In [20]:
np.linspace(start=2, stop=3, num=10, endpoint=True, retstep=False)

array([2.        , 2.11111111, 2.22222222, 2.33333333, 2.44444444,
       2.55555556, 2.66666667, 2.77777778, 2.88888889, 3.        ])

In [23]:
j=np.arange(start=1, stop=10, step=2);print(j)

[1 3 5 7 9]


In [27]:
j=np.arange(start=10, stop=1, step=-2);print(j)

[10  8  6  4  2]


In [35]:
m=np.ones((3,4));print(m)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [36]:
m=np.zeros((3,4));print(m)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [37]:
np.random.rand(3)

array([0.19157884, 0.69953326, 0.63135399])

In [38]:
np.random.rand(3,2)

array([[0.19190743, 0.41463231],
       [0.4346127 , 0.85107151],
       [0.91980075, 0.52123367]])

In [39]:
n=np.logspace(1, 10, num=5, endpoint=True, base=10 );print(n)

[1.00000000e+01 1.77827941e+03 3.16227766e+05 5.62341325e+07
 1.00000000e+10]


In [53]:
np.array([1,2,3])

array([1, 2, 3])

In [54]:
np.array([1,2,3]).reshape(3,1)

array([[1],
       [2],
       [3]])

In [5]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]]);print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
b=np.arange(start=1,stop=10).reshape(3,3)

In [11]:
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
np.add(a,b)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [14]:
np.multiply(a,b)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [15]:
np.subtract(a,b)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [16]:
np.divide(a,b)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.remainder(a,b)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [23]:
a[1,1]

5

In [37]:
a[1:2]

array([[4, 5, 6]])

In [44]:
b=a[:2,:2];print(b)

[[1 2]
 [4 5]]


In [46]:
b[1,1]=12;print(b)

[[ 1  2]
 [ 4 12]]


In [47]:
np.transpose(b)

array([[ 1,  4],
       [ 2, 12]])

In [52]:
np.append(a,[[10,11,22]],axis=0)

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9],
       [10, 11, 22]])

In [57]:
col=np.array([1,2,3]).reshape(3,1)

In [58]:
np.append(a,col,axis=1)

array([[ 1,  2,  3,  1],
       [ 4, 12,  6,  2],
       [ 7,  8,  9,  3]])

In [61]:
np.insert(a,1,[13,15,16],axis=0)

array([[ 1,  2,  3],
       [13, 15, 16],
       [ 4, 12,  6],
       [ 7,  8,  9]])

In [62]:
np.delete(a,1,axis=0)

array([[1, 2, 3],
       [7, 8, 9]])

# Matrix

In [69]:
a=np.matrix("1,2,3;4,5,6;7,8,9");print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [71]:
a.shape

(3, 3)

In [72]:
a.shape[0]

3

In [73]:
a.size

9

In [ ]:
np.insert(a,)

In [92]:
col=np.matrix("11,22,33")
row=np.matrix("44,55,66")

In [85]:
np.insert(a,1,col,axis=0)

matrix([[ 1,  2,  3],
        [11, 22, 33],
        [ 4,  5,  6],
        [ 7,  8,  9]])

In [86]:
a[0,1]

2

In [87]:
a[1,:]

matrix([[4, 5, 6]])

In [91]:
a[:,1]

matrix([[2],
        [5],
        [8]])

In [94]:
A=np.matrix(np.arange(0,20)).reshape(5,4)
B=np.matrix(np.arange(20,40)).reshape(5,4)

In [95]:
np.add(A,B)

matrix([[20, 22, 24, 26],
        [28, 30, 32, 34],
        [36, 38, 40, 42],
        [44, 46, 48, 50],
        [52, 54, 56, 58]])

In [96]:
np.subtract(A,B)

matrix([[-20, -20, -20, -20],
        [-20, -20, -20, -20],
        [-20, -20, -20, -20],
        [-20, -20, -20, -20],
        [-20, -20, -20, -20]])

In [98]:
np.dot(A,np.transpose(B))

matrix([[ 134,  158,  182,  206,  230],
        [ 478,  566,  654,  742,  830],
        [ 822,  974, 1126, 1278, 1430],
        [1166, 1382, 1598, 1814, 2030],
        [1510, 1790, 2070, 2350, 2630]])

In [99]:
np.multiply(A,B)

matrix([[  0,  21,  44,  69],
        [ 96, 125, 156, 189],
        [224, 261, 300, 341],
        [384, 429, 476, 525],
        [576, 629, 684, 741]])

In [100]:
np.divide(A,B)

matrix([[0.        , 0.04761905, 0.09090909, 0.13043478],
        [0.16666667, 0.2       , 0.23076923, 0.25925926],
        [0.28571429, 0.31034483, 0.33333333, 0.35483871],
        [0.375     , 0.39393939, 0.41176471, 0.42857143],
        [0.44444444, 0.45945946, 0.47368421, 0.48717949]])

In [106]:
np.linalg.det(np.matrix("1,2;3,4"))

-2.0000000000000004

In [108]:
np.linalg.matrix_rank(A)

2

In [110]:
np.linalg.inv(np.matrix("1,2;3,4"))

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [123]:
np.linalg.solve(np.matrix("3,1,2;3,2,5;6,7,8"),np.matrix("2,-1,3").transpose())

matrix([[ 1.24242424],
        [ 0.81818182],
        [-1.27272727]])